/**
 * Trading Validation Phase - Shared Types
 *
 * All on-chain amounts are BigInt with specific decimal precision:
 * - USDC: 6 decimals
 * - WETH: 18 decimals
 * - ETH: 18 decimals
 *
 * NO JavaScript Number/float for amounts, approvals, minAmountOut, or reconciliation.
 * Serialize BigInt as strings in logs, API responses, and SQLite.
 */

// ═══════════════════════════════════════════════════════════════════════════
// Branded Amount Types
// ═══════════════════════════════════════════════════════════════════════════

/** USDC amount in 6 decimal precision (e.g., 1_000000n = $1.00) */
export type UsdcAmount = bigint;

/** WETH amount in 18 decimal precision */
export type WethAmount = bigint;

/** ETH amount in 18 decimal precision (native gas token) */
export type EthAmount = bigint;

// ═══════════════════════════════════════════════════════════════════════════
// Enums / Union Types
// ═══════════════════════════════════════════════════════════════════════════

/** Trading mode: shadow (simulated) or micro (real $5-$10 trades) */
export type TradingMode = 'shadow' | 'micro';

/** Market regime classification from 1h indicators */
export type RegimeType =
  | 'TRENDING_UP'
  | 'TRENDING_DOWN'
  | 'RANGING'
  | 'VOLATILE'
  | 'UNCERTAIN';

/** Available trading strategies (spot-long only) - EXPANDED for 5%+ monthly returns */
export type StrategyType = 
  | 'trend_pullback' 
  | 'mean_reversion'
  | 'momentum_breakout'  // NEW: trades breakouts above upper Bollinger
  | 'dip_buying';        // NEW: buys dips at major EMA support levels

/** Reason a position was exited */
export type ExitReason =
  | 'stop_loss'
  | 'take_profit'
  | 'time_stop'
  | 'regime_exit'
  | 'kill_switch'
  | 'operator'
  | 'safe_mode';

/** Transaction intent lifecycle states */
export type IntentState =
  | 'created'
  | 'approval_pending'
  | 'approval_submitted'
  | 'swap_pending'
  | 'confirmed'
  | 'reverted'
  | 'dropped'
  | 'cancelled'
  | 'replaced';

// ═══════════════════════════════════════════════════════════════════════════
// Market Data Types
// ═══════════════════════════════════════════════════════════════════════════

/** OHLCV candle data for a single period */
export interface CandleData {
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

/** Market events emitted by MarketDataManager */
export type MarketEvent =
  | { type: 'candle_close'; timeframe: '15m' | '1h'; candle: CandleData }
  | { type: 'price_move'; magnitude: number }
  | { type: 'volume_spike'; zScore: number }
  | { type: 'regime_change'; from: RegimeType; to: RegimeType }
  | { type: 'periodic_eval' }; // Timer-based evaluation for quiet markets

// ═══════════════════════════════════════════════════════════════════════════
// Core Trading Interfaces
// ═══════════════════════════════════════════════════════════════════════════

/** A trade signal generated by the StrategyEngine (TTL 60s) */
export interface TradeCandidate {
  id: string;
  strategy: StrategyType;
  pair: 'WETH/USDC';
  direction: 'long'; // spot-long only
  confidence: number; // 0-1, deterministic
  stopDistanceFraction: number;
  takeProfitFraction: number;
  regime: RegimeType;
  createdAt: number; // Unix ms
  expiresAt: number; // createdAt + 60_000
}

/** An executable quote from QuoterV2 or aggregator (TTL configurable) */
export interface ExecutableQuote {
  source: 'quoter_v2' | 'aggregator';
  amountIn: bigint;
  amountOut: bigint;
  priceImpactBps: number;
  gasEstimate: bigint; // in wei
  gasUsd: number;
  timestamp: number;
  poolFeeIncluded: boolean; // QuoterV2 = true
  externalFees: bigint; // aggregator-specific fees
  ttl: number; // max age in ms
}

/** A trade that has been sized and is ready for simulation */
export interface SizedTrade {
  candidate: TradeCandidate;
  sizeUsdc: UsdcAmount;
  riskBudget: UsdcAmount;
  stopDistance: number;
  entryQuote: ExecutableQuote;
  minAmountOut: WethAmount;
}

/** An open or closed trading position */
export interface Position {
  id: string;
  intentId: string;
  entryPrice: number;
  entryTimestamp: number;
  sizeUsdc: UsdcAmount;
  sizeWeth: WethAmount;
  stopLoss: number; // price
  takeProfit: number; // price
  maxHoldingMs: number;
  entryRegime: RegimeType;
  strategy: StrategyType;
  exitReason?: ExitReason;
  exitPrice?: number;
  exitTimestamp?: number;
  grossPnl?: UsdcAmount;
  netPnl?: UsdcAmount;
  mfe?: number; // max favorable excursion %
  mae?: number; // max adverse excursion %
}

/** Transaction intent for single-writer nonce management */
export interface TransactionIntent {
  id: string; // idempotent
  state: IntentState;
  nonce: number;
  txHash?: string;
  contractAddress: string;
  functionName: string;
  gasLimit: bigint;
  maxFeePerGas?: bigint;
  maxPriorityFeePerGas?: bigint;
  createdAt: number;
  updatedAt: number;
  blockNumber?: number;
  revertReason?: string;
}

/** Current bankroll allocation state */
export interface BankrollState {
  totalUsdc: UsdcAmount;
  activeUsdc: UsdcAmount;
  reserveUsdc: UsdcAmount;
  unrealizedPnl: UsdcAmount; // signed
  dailyRealizedPnl: UsdcAmount; // signed
  dailyGasSpent: UsdcAmount;
  experimentTotalPnl: UsdcAmount; // signed
}

/** Result of post-operation balance reconciliation */
export interface ReconciliationResult {
  matched: boolean;
  expectedUsdc: UsdcAmount;
  actualUsdc: UsdcAmount;
  expectedWeth: WethAmount;
  actualWeth: WethAmount;
  deviationUsdc: UsdcAmount;
  gasEthSpent: EthAmount;
  gasUsdEquivalent: UsdcAmount;
  allowanceVerified?: boolean;
}
