/**
 * Rejection Normalizer
 *
 * Normalizes raw rejection reason strings from pipeline components into
 * consistent keys for storage in the `rejection_reasons` table.
 *
 * Handles three categories:
 *   1. Gate rejection reasons (8 raw strings → 8 normalized keys)
 *   2. Position sizing rejection reasons (4 keys)
 *   3. Strategy no-signal sub-reason detection (15 sub-reason keys)
 *
 * Requirements: 3.1, 3.2, 3.3, 3.4
 */

import type { Indicators } from '../trading-validation/strategy-engine.js';
import type { RegimeType } from '../trading-validation/types.js';
import type { StrategyEngineConfig } from '../trading-validation/config.js';

// ═══════════════════════════════════════════════════════════════════════════
// Gate Rejection Normalization (Requirement 3.1)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Mapping from raw gate rejection reason strings to normalized keys.
 * These raw strings come from `GateResult.rejectReasons` in the pipeline.
 */
const GATE_REASON_MAP: Record<string, string> = {
  'Net profit below minimum USD': 'profit_below_min_usd',
  'Net profit below minimum bps': 'profit_below_min_bps',
  'Entry quote stale': 'entry_quote_stale',
  'Exit quote stale': 'exit_quote_stale',
  'Entry price impact too high': 'entry_impact_high',
  'Exit price impact too high': 'exit_impact_high',
  'Gas exceeds budget': 'gas_exceeds_budget',
  'Expected profit exceeds sanity limit': 'profit_sanity_fail',
};

/**
 * Normalizes a raw gate rejection reason string to a consistent key.
 * Returns the normalized key or `unknown_gate_reason` if not recognized.
 */
export function normalizeGateRejection(rawReason: string): string {
  return GATE_REASON_MAP[rawReason] ?? 'unknown_gate_reason';
}

/**
 * Normalizes an array of raw gate rejection reasons.
 * Returns an array of normalized keys (one per input reason).
 */
export function normalizeGateRejections(rawReasons: string[]): string[] {
  return rawReasons.map(normalizeGateRejection);
}

/**
 * Returns all known gate rejection normalized keys.
 */
export function getGateRejectionKeys(): string[] {
  return Object.values(GATE_REASON_MAP);
}

// ═══════════════════════════════════════════════════════════════════════════
// Position Sizing Rejection Normalization (Requirement 3.2)
// ═══════════════════════════════════════════════════════════════════════════

/** Valid position sizing rejection keys */
export type PositionSizingRejectionKey =
  | 'size_below_minimum'
  | 'size_exceeds_max'
  | 'kelly_zero'
  | 'bankroll_too_low';

const POSITION_SIZING_KEYS: ReadonlySet<string> = new Set<string>([
  'size_below_minimum',
  'size_exceeds_max',
  'kelly_zero',
  'bankroll_too_low',
]);

/**
 * Validates that a position sizing rejection key is one of the known keys.
 * Returns the key if valid, or `unknown_sizing_reason` if not recognized.
 */
export function normalizePositionSizingRejection(reason: string): string {
  return POSITION_SIZING_KEYS.has(reason) ? reason : 'unknown_sizing_reason';
}

/**
 * Returns all known position sizing rejection keys.
 */
export function getPositionSizingRejectionKeys(): PositionSizingRejectionKey[] {
  return [...POSITION_SIZING_KEYS] as PositionSizingRejectionKey[];
}

// ═══════════════════════════════════════════════════════════════════════════
// Strategy Sub-Reason Detection (Requirements 3.3, 3.4)
// ═══════════════════════════════════════════════════════════════════════════

/** All possible strategy sub-reason keys */
export type StrategySubReasonKey =
  // General (checked first in priority order)
  | 'warmup_incomplete'
  | 'position_open'
  | 'regime_not_actionable'
  | 'cooldown_active'
  // Trend Pullback specific
  | 'trend_ema_distance'
  | 'trend_rsi_out_of_range'
  | 'trend_volume_low'
  | 'trend_ema_order'
  | 'trend_price_below_ema50'
  // Mean Reversion specific
  | 'mean_rev_above_bb'
  | 'mean_rev_rsi_high'
  | 'mean_rev_volume_low'
  | 'mean_rev_atr_ratio';

/**
 * Detects the specific sub-reason why no signal was generated by the strategy engine.
 *
 * Evaluates conditions in priority order:
 *   1. warmup_incomplete — indicators not available (insufficient candle history)
 *   2. position_open — a position is already active
 *   3. regime_not_actionable — regime is not TRENDING_UP or RANGING
 *   4. cooldown_active — cooldown period not elapsed
 *   5. Strategy-specific conditions (Trend Pullback or Mean Reversion)
 *
 * @param indicators - Current 15m indicators (null if not available)
 * @param regime - Current regime classification
 * @param config - Strategy engine configuration
 * @param positionOpen - Whether a position is currently open
 * @param cooldownRemaining - Milliseconds remaining in cooldown (0 = ready)
 * @returns The normalized sub-reason key
 */
export function detectStrategySubReason(
  indicators: Indicators | null,
  regime: RegimeType,
  config: StrategyEngineConfig,
  positionOpen: boolean,
  cooldownRemaining: number,
): StrategySubReasonKey {
  // Priority 1: warmup incomplete
  if (!indicators) {
    return 'warmup_incomplete';
  }

  // Priority 2: position already open
  if (positionOpen) {
    return 'position_open';
  }

  // Priority 3: regime not actionable
  if (regime !== 'TRENDING_UP' && regime !== 'RANGING') {
    return 'regime_not_actionable';
  }

  // Priority 4: cooldown active
  if (cooldownRemaining > 0) {
    return 'cooldown_active';
  }

  // Priority 5: Strategy-specific condition failures
  if (regime === 'TRENDING_UP') {
    return detectTrendPullbackSubReason(indicators, config);
  }

  if (regime === 'RANGING') {
    return detectMeanReversionSubReason(indicators, config);
  }

  // Fallback (should not be reached given regime check above)
  return 'regime_not_actionable';
}

/**
 * Detects which Trend Pullback condition failed (evaluated in strategy order).
 */
function detectTrendPullbackSubReason(
  indicators: Indicators,
  config: StrategyEngineConfig,
): StrategySubReasonKey {
  const { lastPrice, ema20, ema50, rsi14, volumeZScore } = indicators;

  // Condition: price within 0.5% of EMA20
  const distanceToEma20Pct = Math.abs(lastPrice - ema20) / ema20;
  if (distanceToEma20Pct > 0.005) {
    return 'trend_ema_distance';
  }

  // Condition: RSI in [35, 50]
  if (rsi14 < 35 || rsi14 > 50) {
    return 'trend_rsi_out_of_range';
  }

  // Condition: volumeZ > threshold
  if (volumeZScore <= config.volumeZThreshold) {
    return 'trend_volume_low';
  }

  // Condition: EMA20 > EMA50
  if (ema20 <= ema50) {
    return 'trend_ema_order';
  }

  // Condition: close > EMA50
  if (lastPrice <= ema50) {
    return 'trend_price_below_ema50';
  }

  // All conditions passed — should not happen if no signal was generated
  // but return the last condition as default
  return 'trend_price_below_ema50';
}

/**
 * Detects which Mean Reversion condition failed (evaluated in strategy order).
 */
function detectMeanReversionSubReason(
  indicators: Indicators,
  config: StrategyEngineConfig,
): StrategySubReasonKey {
  const { lastPrice, rsi14, volumeZScore, bollingerBands } = indicators;

  // Condition: price <= lower Bollinger
  if (lastPrice > bollingerBands.lower) {
    return 'mean_rev_above_bb';
  }

  // Condition: RSI < 30
  if (rsi14 >= 30) {
    return 'mean_rev_rsi_high';
  }

  // Condition: volumeZ > threshold
  if (volumeZScore <= config.volumeZThreshold) {
    return 'mean_rev_volume_low';
  }

  // Condition: ATR ratio check (final condition)
  return 'mean_rev_atr_ratio';
}

/**
 * Returns all known strategy sub-reason keys.
 */
export function getStrategySubReasonKeys(): StrategySubReasonKey[] {
  return [
    'warmup_incomplete',
    'position_open',
    'regime_not_actionable',
    'cooldown_active',
    'trend_ema_distance',
    'trend_rsi_out_of_range',
    'trend_volume_low',
    'trend_ema_order',
    'trend_price_below_ema50',
    'mean_rev_above_bb',
    'mean_rev_rsi_high',
    'mean_rev_volume_low',
    'mean_rev_atr_ratio',
  ];
}
